main/urls.py
from django import urls
from django.contrib import admin
from django.db import router
from django.urls import path,include
from . import views
from django.contrib.auth.views import PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView

''' Serilizers Configiration '''
from rest_framework import routers

''' api Routes '''
router = routers.DefaultRouter()
router.register('product_api', views.ProductViewSet )
router.register('wanted_products_api',views.WantedProductViewSet)
router.register('transports_api',views.TransportViewSet)
router.register('transport_order_api',views.TransportOrderViewSet)
router.register('real_price_api',views.ProductPriceViewSet)

urlpatterns = [
    path('',views.homepage,name = 'indexpage'),
    path('update_profile/', views.update_profile,name='update_profile'),
    path('start/loginuser/',views.login_view,name='loginuser'),
    path('logoutuser/',views.logoutuser,name='logoutuser'),
    path('start/registercustomer/',views.registercustomer,name = 'registercustomer'),
    path('update/', views.CustomUserView.as_view(), name='update_customer'),
    path('profile_detail/', views.ProfileDetailView.as_view(), name='profile_detail'),
    path('start/homepage/',views.homepage,name='homepage'),
    path('start/productlist',views.productlist,name = 'productlist'),
    path('vertifyaccount/',views.vertifyaccount,name = 'vertifyaccount'),
    path('resetoptions/',views.resetoptions,name = 'resetoptions'),

    path('password_reset/',PasswordResetView.as_view(template_name = 'reset_password.html'),name='password_reset'),
    path('password_reset/done',PasswordResetDoneView.as_view(template_name = 'password_reset_done.html'),name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/' ,PasswordResetConfirmView.as_view(template_name = 'password_reset_confirm.html'),name = 'password_reset_confirm'),

    path('password_reset_complete/',PasswordResetCompleteView.as_view(template_name = 'password_reset_complete.html'),name='password_reset_complete'),
    path('search_item/',views.search_item,name = 'search_item'),
    path('about_us/',views.about_us,name = 'about_us'),


    path('api/', include(router.urls))
    
    # path('registerSeller/',views.registerSeller,name='regiseter_seller'),
    # path('registerTransporter/',views.registerTransporter,name='register_transplorter'),
    # path('workers_registration/',views.BranchAdmin,name='workers_registration')
  
 
]

management/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    path('create_product/', views.add_product,name='create_product'),
    path('user_products/',views.user_products,name = 'user_products'),
    path('product_detail/<int:pk>/',views.product_detail,name='product_detail'),
    path('contact/',views.contactus,name='contactus'),
    path('order_product/<int:pk>/',views.order_product,name='order_product'),
    path('update_product/<int:pk>/',views.update_product,name='update_product'),
    path('delete/<int:pk>/',views.delete_product,name='delete'),
    path('add_wanted_product/',views.add_wanted_product,name = 'add_wanted_product'),
    path('wantedproductlist/',views.wantedproductlist,name = 'wantedproductlist'),
    path('wanted_product_detail/<int:pk>/',views.wanted_product_detail,name= 'wanted_product_detail'),
    path('change_status/<int:pk>/',views.change_status,name = 'change_status'),
    path('delete_orders/<int:pk>/',views.delete_orders,name ='delete_orders'),
    path('add_catagory/',views.add_catagory,name = 'add_catagory'),
    path('transport_add/',views.transport_add,name = 'transport_add'),
    path('display_transports/',views.display_transports,name ='display_transports'),
    path('transport_product_detail/<int:pk>/',views.transport_product_detail,name = 'transport_product_detail'),
    path('order_Transport/<int:pk>/',views.order_Transport, name = 'order_Transport'),
    path('change_status_transport/<int:pk>/',views.change_status_transport,name = 'change_status_transport'),
    path('search_transport/',views.search_transport,name = 'search_transport'),
    path('update_transport/<int:pk>/',views.update_transport,name = 'update_transport'),
    path('delete_transports/<int:pk>',views.delete_transports,name = 'delete_transports')
   # path('commentreview/',views.commentreview,name='commentreview')
    # path('product_detail2/<int:pk>/',views.ProductDetail.as_view(), name='product_detail')
]

test2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
# from rest_framework.schemas import get_schema_view

urlpatterns = [
    path('real_price/', include('real_price.urls')),
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('manage_user/',include('management.urls')),
    # path('schema',get_schema_view(
    #     title = 'DRIMS API GETWAY',
    #     description = 'API for DRIMS Project',
    #     version = '1.0.0',
    # ),name = 'openapi-schema')
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

admin.site.site_header = "DRIMS ADMIN PANEL"
admin.site.index_title = 'DRIMS ADMIN PANEL'
admin.site.site_title = 'DRIMS ADMIN PANEL'

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse



role = (
     ('Producer','Producer'),
     ('Buyer','Buyer'),
     ('Transport-Provider','Transport-Provider'),
     ('empty','empty'),
     ('Price_teller','Price_teller')
)
class CustomUser(AbstractUser):
    phone = models.CharField(max_length=100)
    registerddate = models.DateTimeField(auto_now_add = True)
    is_banned = models.BooleanField(default=False)
    Email_Adress = models.CharField(max_length=1000)
    role = models.CharField(choices = role,max_length=100,default='empty',null=True,blank=True)
    phone_vertified = models.BooleanField(default=False)
    email_vertified = models.BooleanField(default=False)
    is_premium_account = models.BooleanField(default=False)
    Adress =models.CharField(max_length=200,null=True,blank =True)
    optional_adress = models.CharField(max_length=200)



    


    

class Profile(models.Model):
     user = models.OneToOneField(CustomUser,null=True,on_delete=models.CASCADE,related_name ='profile')
     # product = models.CharField(max_length =100)
     pic = models.ImageField(upload_to = 'images', default='media/images/app4.jpg', blank =True,null = True)
     bio = models.TextField(null=True,blank=True)
     licencecopy = models.FileField(upload_to='media/documents',null=True,blank=True)
     idimg = models.ImageField(upload_to = 'media/docimages',blank =True,null = True)
     #role = models.CharField(max_length=100,choices=choices)

     def __str__(self):
          return self.user.username
     
         
     

management/DRIMS/models.py
from django.db import models
from main.models import CustomUser
from django.urls import reverse

# Create your models here.
sell_type = (
    ('per single','persingle'),
    ('per pack','perpack')
)


class Products(models.Model):
    user = models.ForeignKey(CustomUser,null=True,on_delete=models.PROTECT,related_name ='product_user')
    product_name = models.CharField(max_length=250)
    catagory = models.ForeignKey('ProductCatagory',on_delete = models.PROTECT)
    description = models.TextField()
    product_image = models.ImageField(upload_to = 'media/images/')
    post_date = models.DateTimeField(auto_now_add =True)
    amount = models.CharField(max_length=100,choices = sell_type)
    specific_adress = models.CharField(max_length=250,null=True,blank=True)
    price = models.FloatField(default =1.0)

    class Meta:
        ordering = ('-post_date',)

    def get_absloute_url(self):
        return reverse('product_detail', args=(str(self.pk),))
    
    def __str__(self):
        return self.product_name

need = (
    ('single','single'),
    ('many','many'),
    ('unknown','unknown')
)
class WantedProducts(models.Model):
    user = models.ForeignKey(CustomUser,null=True,on_delete=models.PROTECT,related_name ='wanted_product_user')
    product_name = models.CharField(max_length=250)
    #catagory = models.ForeignKey('ProductCatagory',on_delete = models.PROTECT)
    description = models.TextField()
    product_image = models.ImageField(upload_to = 'media/images/')
    post_date = models.DateTimeField(auto_now_add =True)
    amount_need = models.CharField(max_length=100,choices = need)
    specific_adress = models.CharField(max_length=250,null=True,blank=True)
    price_range = models.CharField(max_length=100)

    class Meta:
        ordering = ('-post_date',)

    def get_absloute_url(self):
        return reverse('wanted_product_detail', args=(str(self.pk),))
    
    def __str__(self):
        return self.product_name


class ProductCatagory(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class CommentReview(models.Model):
    commetned_by = models.ForeignKey(CustomUser,on_delete=models.PROTECT,related_name ='commenter',null=True)
    comment = models.TextField()
    product_id = models.IntegerField()
    commented_date = models.DateTimeField(auto_now_add =True)


    class Meta:
        ordering = ('-commented_date',)

    def __str__(self):
        return self.comment

class Message(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.PROTECT,related_name ='messenger',null=True)
    full_name = models.CharField(max_length=250)
    email = models.CharField(max_length=250)
    subject = models.CharField(max_length=300)
    message = models.TextField()

    def __str__(self):
        return (f'Message Sent From {self.user.username}')

class ProductOrders(models.Model):
     ordered_item = models.ForeignKey(Products,on_delete = models.PROTECT,related_name = 'ordered_product')
     ordered_by = models.ForeignKey(CustomUser,null=True,on_delete=models.PROTECT,related_name ='product_ordered_by')
     prouct_owner = models.ForeignKey(CustomUser,null= True,on_delete = models.PROTECT,related_name = 'product_owner')
     order_date = models.DateTimeField(auto_now_add = True)
     order_destination = models.CharField(max_length = 250,null=True,blank =True)
    #  message = models.TextField(null=True,blank = True)
     order_source_adress = models.CharField(max_length = 250,null=True,blank=True)
     orderer_optional_adress = models.CharField(max_length = 250,null=True,blank=True)
     accecpted = models.BooleanField(default = False)
     
     class Meta:
         ordering = ('-order_date',)

     def __str__(self):
         return self.ordered_item.product_name
    

class TransortOrders(models.Model):
     ordered_by = models.ForeignKey(CustomUser,null=True,on_delete=models.PROTECT,related_name ='transport_ordered_by')
     transport_owner = models.ForeignKey(CustomUser,null= True,on_delete = models.PROTECT,related_name = 'transport_owner')
     order_date = models.DateTimeField(auto_now_add = True)
     message = models.TextField(null=True,blank = True)
     order_source_adress = models.CharField(max_length = 250,null=True,blank=True)
     orderer_optional_adress = models.CharField(max_length = 250,null=True,blank=True)
     
     class Meta:
         ordering = ('-order_date',)

     def __str__(self):
         return self.transport_owner
    



    

management/forms.py
from .models import *
from django.forms import ModelForm


class AddProducts(ModelForm):
    class Meta:
        model = Products
        fields = ['user','product_name','description','product_image','amount','specific_adress','catagory','price']
    

class AddCatagory(ModelForm):
    class Meta:
        model = ProductCatagory
        fields = '__all__'

class AddWantedProducts(ModelForm):
    class Meta:
        model = WantedProducts
        fields = ['user','product_name','description','product_image','amount_need','specific_adress','price_range']

class CommentRev(ModelForm):
    class Meta:
        model = CommentReview
        fields = ['commetned_by','comment','product_id']

class MessageSend(ModelForm):
    class Meta:
        model = Message
        fields = ['user','full_name','subject','message','email']

class OrderUserProduct(ModelForm):
    class Meta:
        model = ProductOrders
        fields = ['ordered_item','ordered_by','prouct_owner','order_destination','order_source_adress','orderer_optional_adress']

class TransportOrdersAdd(ModelForm):
    class Meta:
        model = TransportOrders
        fields = ['ordered_by','transport_owner','message','orderer_optional_adress']

class AddTransports(ModelForm):
    class Meta:
        model = Transports
        fields = ('user','transport_name','description','transport_image','specific_adress','price')

management/templates/buyer_orders.html
{% extends 'base copy.html' %}
{% load static%}
    {%block content%}


    <div class="container" style="margin-top:100px;">

      {% for message in messages %}

                {% if message.success %}
                <div class="alert alert-danger fade in alert-dismissible show mr-5 ml-5 mt-2" style="margin-top:18px;">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true" style="font-size:20px">×</span>
                  </button>   <strong>Dear {{request.user}} </strong> {{ message }}.
                </div>
                {%endif%}
                <div class="alert alert-success fade in alert-dismissible show mr-5 ml-5 mt-2" style="margin-top:18px;">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true" style="font-size:20px">×</span>
                  </button>   <strong>Dear {{request.user}} </strong> {{ message }}.
                </div>
                
                  

    {% endfor %}

    <h2 style="color: limegreen;margin-bottom: 50px;margin-left: 28%;">You have Ordered
      
      {% if order%}
      {{order}}
      {%else%}
         No
      {%endif%}      
      products </h2>

    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col"> Product Image</th>
          <th scope="col">Product Name</th>
          <th scope="col">Price</th>
          <th scope="col">Product Owner</th>
          <th scope="col">status</th>
          <th scope="col">Delete</th>
          
          

        </tr>
      </thead>

     
      <tbody>
        {%for pr in orders%}
        <tr>
    
          <td><img style = 'width: 50px;height:auto;' src='{{pr.ordered_item.product_image.url}}'>  </img></td>
          <td>{{pr.ordered_item}}</td>
          <td>{{pr.ordered_item.price}} $</td>
          <td>{{pr.prouct_owner}}</td>
          {%if pr.accecpted%}
          <td><a href="#" class="btn btn-success">Accepted</a></td>
          {%else%}
          <td><a href="#" class="btn btn-danger">Pending</a></td>
          {%endif%}
          <td><a href="{% url 'delete_orders' pr.pk %}" class="btn btn-danger">Delete</a></td>
        </tr>
        {%endfor%}
      </tbody>
     

    </table>


    {%endblock%}

management/templates/ch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   
  saved
</body>
</html>

management/templates/product_add.html
{% extends 'base copy.html' %}
{%block content%}
<div id="preloader">
  <div class="jumper">
      <div></div>
      <div></div>
      <div></div>
  </div>
</div>


<div class="container" style="margin-top: 150px">
   
  <div style="margin-left: 28%;"><a class="navbar-brand ml-5" href="#"><h2>Add  <em>Product</em></h2></a></div>
    <form method="POST" enctype ='multipart/form-data' action="{% url 'create_product' %}">
      {% csrf_token %}
      {% for message in messages %}
      <div class="alert alert-success fade in alert-dismissible show mr-5 ml-5 mt-2" style="margin-top:18px;">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
           <span aria-hidden="true" style="font-size:20px">×</span>
         </button>   <strong>Dear {{request.user}} </strong> {{ message }}.
       </div>
        
  
      {% endfor %}
    <input type="hidden" class="form-control" name='user' value ={{request.user.id}} placeholder="Product name">
    <div class="row">

     

       <div class="col-lg-12 col-md-12 col-sm-12 ml-5 mb-3 mr-5">
        <fieldset>
          <label>Amount</label>
          <select class="custom-select mr-sm-2" name = 'amount' id="inlineFormCustomSelect">
            <option value="" selected="">---------</option>
             <option value="per single">persingle</option>
             <option value="per pack">perpack</option>
           </select>
         
        </fieldset>
      </div>

      <div class="col-lg-12 col-md-12 col-sm-12 ml-5 mb-3 mr-5">
        <fieldset>
          
          <label class="mr-sm-2" for="inlineFormCustomSelect">catagory</label>
                 
                    
          <select name="catagory"  selected ='' class="custom-select mr-sm-2" required="" id="id_catagory">
            {% for item in cat%}
                 <option value="{{item.id}}">{{item}}</option>

          {%endfor%}n>
          
          </select>
         
        </fieldset>
      </div>

      <div class="col-lg-12 col-md-12 col-sm-12 ml-5 mb-3 mr-5">
        <fieldset>
          <input name="product_name" type="text" class="form-control" id="name" placeholder="product_name" required="">
         
        </fieldset>
      </div>
     

      <div class="col-lg-12 col-md-12 col-sm-12 ml-5 mb-3 mr-5">
        <fieldset>
          <input name="specific_adress" type="text" class="form-control" id="email" placeholder="specific_adress" required="">
        </fieldset>
      </div>
      
      <div class="col-lg-12 col-md-12 col-sm-12 ml-5 mb-3 mr-5">
        <fieldset>
          <input type="number" class="form-control" name='price' min='1' placeholder="price Greter than 1" required>
        </fieldset>
      </div>

      <div class="col-lg-12 col-md-12 col-sm-12 ml-5 mb-3 mr-5">
        <div class="input-group-prepend mb-2">
          <span class="input-group-text">Upload Product Image</span>
        </div>
        <fieldset>
          <input type="file" name ='product_image' class="form-control" name="pic" accept="image/*" id="id_pic">
        </fieldset>
      </div>

      <div class="col-lg-12 ml-5 mb-3 mr-5">
        <fieldset>
          <textarea name="description" rows="6" class="form-control" id="message" placeholder="Your description" required=""></textarea>
        </fieldset>
      </div>

      <div class="col-lg-12 ml-5 mb-3 mr-5 " style="float: right !important;">
        <fieldset>
          <button type="submit" id="form-submit" class="filled-button btn btn-secondary">Add Product</button>
        </fieldset>
      </div>

    </div>
  </form>

  <form method = 'POST' action="{% url 'add_catagory' %}" >
    {% csrf_token %}
    <div class="col-lg-12 col-md-12 col-sm-12 ml-5 mb-3 mr-5">
      <label class="mr-sm-2" for="inlineFormCustomSelect">Add catagory</label>
      <fieldset>
        <input name="name" type="text" class="form-control" id="email" placeholder="Catagory Name" required="">
      </fieldset>
    </div>
    
    <button type="submit" id="form-submit" class="filled-button btn btn-secondary ml-5">Add catagory</button>
  </form>
  </div>
{%endblock%}

management/templates/product_update.html
{% extends 'base copy.html' %}
{% load static%}
    {%block content%}
<!-- <div style="margin-top: 100px;">
    <form method="POST" action="{% url 'update_product' pk %}">
    {% csrf_token%}
        {{form1.as_p}}
        <button type="submit"> Update</button>
    </form>
</div> -->

    <form method="POST" enctype ='multipart/form-data' action="{% url 'update_product' pk %}" >
        {% csrf_token %}
<div  style="background-color: #f5f6fa; margin:100px !important;">
    <div class="container mt-5" style="box-shadow:0 0 10px rgba(0,0,0,.15)">
        <div class="row gutters">
        <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
        <div class="card h-100">
            <div class="card-body">
                <div class="account-settings">
                    <div class="user-profile">
                        
                            
                                <img height="300" width = "auto" class="p-3"  src="{{product.product_image.url}}" alt="{{request.user.first_name}} {{request.user.last_name}}">
                            
                            
                        <h5 class="user-name">{{product.product_name}}</h5>
                        <h6 class="user-email">{{product.user.username}}</h6>
                        <a href="{{product.product_image.url}}">Image Link</a>
                    </div>
                    <div class="about">
                        <h5>About</h5>
                        <p>{{product.description}}.</p>
                    </div>
                </div>
            </div>
        </div>
        </div>
        <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
        <div class="card h-100">
            <div class="card-body">
                <div class="row gutters">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                        <h6 class="mb-2 text-primary">Prouduct Details</h6>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="form-group">
                            <input type="hidden" name="user" class="form-control" id="website" value="{{request.user.pk}}">
                        </div>
                        <div class="form-group">
                            <label for="fullName">Product Name</label>
                            <input type="text" class="form-control" id="fullName" name ="product_name"  value="{{product.product_name}}">
                        </div>

                        
                    </div>

                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="form-group">
                            <label for="phone">Amount</label>
                            <select name="amount" class="custom-select mr-sm-2" required="" id="id_catagory">
                                <option value="">---------</option>
                              
                                <option value="per single">persingle</option>
                              
                                <option value="per pack" selected="">perpack</option>
                              
                              </select>
                        </div>
                    </div>

                    
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="form-group">
                            
                    <label class="mr-sm-2" for="inlineFormCustomSelect">catagory</label>
                 
                    
                    <select name="catagory"  selected ='' class="custom-select mr-sm-2" required="" id="id_catagory">
                      {% for item in cat%}
                           <option value="{{item.id}}">{{item}}</option>
          
                    {%endfor%}n>
                    
                    </select>
                        </div>
                    </div>

                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="form-group">
                            <label for="website">Specific Adress</label>
                            <input type="text" name="specific_adress" class="form-control" id="website" value="{{product.specific_adress}}">
                        </div>
                    </div>
                   

                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="form-group">
                            <label for="website">Price</label>
                            <input   class="custom-select mr-sm-2"  name="price"  min="1.0" value = "{{product.price}}" required="" id="id_price">
                        </div>
                    </div>
                 

                    

                </div>
                <div class="row gutters">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                        <h6 class="mt-3 mb-2 text-primary">Other Info</h6>
                    </div>

                
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="form-group">
                            <label for="sTate">Product Image </label>
                            <!-- <input type="text" class="form-control" id="sTate" placeholder="Enter State"> -->
                            <input type="file" class="form-control" name="product_image" accept="image/*" id="id_pic">
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="form-group">
                            <label for="zIp">Product Description</label>
                            <!-- <input type="text" class="form-control" id="zIp" placeholder="Zip Code"> -->
                            <textarea name="description" class="form-control" value="{{product.description}}"  cols="20" rows="1" id="id_bio"></textarea>
                        </div>
                    </div>

                </div>
                <div class="row gutters">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                        <div class="text-right">
                            <a href="{% url 'homepage' %}" class="btn btn-secondary">Home</a>
                            <button type ="submit"  name="submit" class="btn btn-primary">Update Product</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
        </div>
        </div>
    </div>
    </form>    

{%endblock%}

management/templates/transport_update.html
{% extends 'base copy.html' %}
{% load static%}
    {%block content%}


    <form method="POST" enctype ='multipart/form-data' action="{% url 'update_transport' pk %}" >
        {% csrf_token %}
<div  style="background-color: #f5f6fa; margin:100px !important;">
    <div class="container mt-5" style="box-shadow:0 0 10px rgba(0,0,0,.15)">
        <div class="row gutters">
        <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
        <div class="card h-100">
            <div class="card-body">
                <div class="account-settings">
                    <div class="user-profile">
                           <div style="overflow: hidden;">
                            
                                <img height="auto" width = "200" class="p-3" style ="left: 0px !important; " src="{{product.transport_image.url}}" alt="{{request.user.first_name}} {{request.user.last_name}}">
                            </div>
                            
                            
                        <h5 class="user-name">{{product.transport_name}}</h5>
                        <h6 class="user-email">{{product.user.username}}</h6>
                        <a href="{{product.transport_image.url}}">Image Link</a>
                    </div>
                    <div class="about">
                        <h5>About</h5>
                        <p>{{product.description}}.</p>
                    </div>
                </div>
            </div>
        </div>
        </div>
        <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
        <div class="card h-100">
            <div class="card-body">
                <div class="row gutters">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                        <h6 class="mb-2 text-primary">Transport Details</h6>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="form-group">
                            <input type="hidden" name="user" class="form-control" id="website" value="{{request.user.pk}}">
                        </div>
                        <div class="form-group">
                            <label for="fullName">Transport Name</label>
                            <input type="text" class="form-control" id="fullName" name ="transport_name"  value="{{product.transport_name}}">
                        </div>

                        
                    </div>

                    
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="form-group">
                            <label for="website">Specific Adress</label>
                            <input type="text" name="specific_adress" class="form-control" id="website" value="{{product.specific_adress}}">
                        </div>
                    </div>
                   

                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="form-group">
                            <label for="website">Price</label>
                            <input   class="custom-select mr-sm-2"  name="price"  min="1.0" value = "{{product.price}}" required="" id="id_price">
                        </div>
                    </div>
                 

                    

                </div>
                <div class="row gutters">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                        <h6 class="mt-3 mb-2 text-primary">Other Info</h6>
                    </div>

                
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="form-group">
                            <label for="sTate">Transport Image </label>
                            <input type="file" class="form-control" name="transport_image" accept="image/*" id="id_pic">
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="form-group">
                            <label for="zIp">Transport Description</label>
                            <textarea name="description" class="form-control"  cols="20" rows="4" id="id_bio">{{product.description}}</textarea>
                        </div>
                    </div>

                </div>
                <div class="row gutters">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                        <div class="text-right">
                            <a href="{% url 'homepage' %}" class="btn btn-secondary">Home</a>
                            <button type ="submit"  name="submit" class="btn btn-primary">Update Trasport</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
        </div>
        </div>
    </div>
    </form>    

{%endblock%}